### ISSUE TITLE
Macro doesn't do anything

### ISSUE THREAD

**Issue by khisanthax** [T9Air/Klipper_Power_Resume#71]
When I'm in ssh and in the menu for KPR, I press 2 to add logging gcode to a file, it gives me a prompt to type the name of the file. When I clicked on the macro to "log file", no prompt came up to do that. I assumed that a prompt would have come up to ask for the name of the print file or is that automatic now?

**Comment by T9Air** [comment]
Since v3.6.0 is still in development, I have not added the documentation yet. Before clicking on the macro, there should be a drop-down arrow that you can click. When you press it, a box should pop up that you can fill in with the filename, whether you want to log once every layer or every x number of lines, and, if you are skipping per line, how many lines to skip.

**Comment by khisanthax** [comment]
I'll upgrade back to development and then look at the macro again.  I know that I messed up with the downgrade so maybe that's why there's in an arrow allowing for text input.  Thanks!
